name: Check PHP Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - l10n_crowdin_action
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-php-code:
    if: (github.repository == 'joomla/core-translations') || (github.repository != 'joomla/core-translations' && github.event_name != 'schedule')
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check PHP syntax errors
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: '.'

