name: "En_GBLocalise in translations"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - l10n_crowdin_action
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  engb-localise:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Check PR content
        id: build
        run: |
          cd ./joomla_v4/translations/package
          mkdir ./logs
          grep -rn --include \*.php 'En_GBLocalise' | tee ./logs/en_gblocalise_result
          cat ./logs/en_gblocalise_result | wc -l | tee ./logs/files_affected
          awk -F/ '{ print $1 }' ./logs/en_gblocalise_result | sort -u | wc -l | tee ./logs/languagepacks_affected
          aflp=$(head -n 1 ./logs/languagepacks_affected)
          affi=$(head -n 1 ./logs/files_affected)
          echo -n "$aflp" > ./logs/languagepacks_affected
          echo -n "$affi" > ./logs/files_affected
          cat ./logs/en_gblocalise_result

      - name: Save PR number
        if: ${{ always() }}
        run: |
          cd ./joomla_v4/translations/package
          echo -n ${{ github.event.pull_request.number }} | tee ./logs/pr_number
          [ -s ./logs/pr_number ] || gh pr list --limit 1 --repo joomla/core-translations --author app/github-actions --state open --json number --jq .[].number > ./logs/pr_number
          prnumber=$(head -n 1 ./logs/pr_number)
          echo -n "$prnumber" > ./logs/pr_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Save PR sha
        if: ${{ always() }}
        run: echo ${{ github.sha }} | tee ./joomla_v4/translations/package/logs/pr_sha

      - name: fail workflow
        run: |
         if [ -s ./joomla_v4/translations/package/logs/en_gblocalise_result ]; then
         exit 1
         fi

      - name: Upload En_GBLocalise-logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: En_GBLocalise-logs
          path: ./joomla_v4/translations/package/logs

