name: "En_GBLocalise in translations"

on:
  pull_request:
    branches:
      - main-test
    types: [synchronize, created]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  engb-localise:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check PR content
      id: build
      run: |
          cd ./joomla_v4/translations/package
          mkdir ./logs
          grep -rn --include \*.php 'En_GBLocalise' | tee ./logs/en_gblocalise_result
          cat ./logs/en_gblocalise_result | wc -l | tee ./logs/files_affected
          awk -F/ '{ print $1 }' ./logs/en_gblocalise_result | sort -u | wc -l | tee ./logs/languagepacks_affected
          aflp=$(head -n 1 ./logs/languagepacks_affected)
          affi=$(head -n 1 ./logs/files_affected)
          echo -n "$aflp" > ./logs/languagepacks_affected
          echo -n "$affi" > ./logs/files_affected
          cat ./logs/en_gblocalise_result

    - name: Save PR number
      if: ${{ always() }}
      run: echo ${{ github.event.pull_request.number }} | tee ./joomla_v4/translations/package/logs/pr_number
      
    - name: Save PR sha
      if: ${{ always() }}
      run: echo ${{ github.sha }} | tee ./joomla_v4/translations/package/logs/pr_sha

    - name: fail workflow
      run: |
        if [ -f ./joomla_v4/translations/package/logs/en_gblocalise_result ]; then
        exit 1
        fi


    - name: Upload En_GBLocalise-logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: En_GBLocalise-logs
        path: ./joomla_v4/translations/package/logs
