name: J3 Build JoomlaCMSProject
# Controls when the action will run.
on:
  schedule:
    - cron: '0 9,21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
    # Runs the HTTP Request action command - https://github.com/fjogeleit/http-request-action
    - name: Call build URL
      id: BuildV3CMS
      uses: fjogeleit/http-request-action@v1.14.1
      with:
        url: 'https://crowdin.com/api/v2/projects/120642/translations/builds'
        method: 'POST'
        contentType: 'application/json'
        data: '{"targetLanguageIds": [],"skipUntranslatedStrings": true,"skipUntranslatedFiles": false,"exportApprovedOnly": true}'
        bearerToken: ${{ secrets.CROWDIN_NORMAL_PERSONAL_TOKEN }}

    - name: Show Response
      run: echo ${{ steps.BuildV3CMS.outputs.response }}
