name: TEST J4 Download Package Translations Crowdin Action
# Controls when the action will run.
on:
  # Runs once a day at 2:01
  # schedule:
  #  - cron:  '01 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  synchronize-with-crowdin:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GHA_TRANSLATIONBOT_PAT }}

    # Runs the Crowdin action command - https://github.com/crowdin/github-action
    - name: Crowdin Download Afrikaans
      uses: crowdin/github-action@v2.9.1
      with:
        # Option to specify a path to the configuration file, without / at the beginning
        config: 'Configurations/Crowdin-J4-All.yml'
        # Upload sources to Crowdin
        upload_sources: false
        # Make pull request of Crowdin translations
        download_translations: true
        # Download specific language
        download_language: af
        # Only download translated strings
        skip_untranslated_strings: true
        # Include approved translations only in exported files.
        # If not combined with --skip-untranslated-strings option, strings without approval are fulfilled with the source language'
        export_only_approved: true
        # The message of the commit
        commit_message: 'New Afrikaans Crowdin translations by Github Action'
        localization_branch_name: 'l10n_crowdin_package_v4'
        github_user_name: 'joomla-translation-bot'
        github_user_email: 'release+translation-bot@joomla.org'
      env:
        GITHUB_TOKEN: ${{ secrets.GHA_TRANSLATIONBOT_PAT }}
